name: Cypress Tests for Module Updates in Brand Plugin

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
    branches:
      - main
      - trunk
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

  bluehost:
    name: Bluehost Build and Test
    needs: setup
    uses: newfold-labs/workflows/.github/workflows/module-plugin-test.yml@main
    with:
      only-module-tests: true
      plugin-branch: 'enhance/fix-onboarding-tests'
      module-repo: ${{ github.repository }}
      module-branch: ${{ needs.setup.outputs.branch }}
      plugin-repo: "bluehost/bluehost-wordpress-plugin"
    secrets: inherit

  hostgator:
    name: HostGator Build and Test
    needs: setup
    uses: newfold-labs/workflows/.github/workflows/module-plugin-test.yml@main
    with:
      only-module-tests: true
      module-repo: ${{ github.repository }}
      module-branch: ${{ needs.setup.outputs.branch }}
      plugin-repo: "newfold-labs/wp-plugin-hostgator"
    secrets: inherit

  crazydomains:
    name: Crazy Domains Build and Test
    needs: setup
    uses: newfold-labs/workflows/.github/workflows/module-plugin-test.yml@main
    with:
      only-module-tests: true
      module-repo: ${{ github.repository }}
      module-branch: ${{ needs.setup.outputs.branch }}
      plugin-repo: "newfold-labs/wp-plugin-crazy-domains"
    secrets: inherit
